import type { Metadata } from "next";
import LoadingPage from "@/components/utils/LoadingPage";
//clerck auth
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      // style={{
      //   background: "white",
      // }}
    >
      <body
        // style={{
        //   background: "white",
        // }}
      >
        <ClerkProvider>
          <ClerkLoading>
            <LoadingPage />
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </ClerkProvider>
      </body>
    </html>
  );
}
