import type { Metadata } from "next";
import LoadingPage from "@/components/utils/LoadingPage";
//clerck auth
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { StyledEngineProvider } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
    >
      <body
        id={"__next"}
      >
        <ClerkProvider>
          <ClerkLoading>
            <LoadingPage />
          </ClerkLoading>
          <ClerkLoaded>
            <StyledEngineProvider injectFirst>{children}</StyledEngineProvider>
          </ClerkLoaded>
        </ClerkProvider>
      </body>
    </html>
  );
}
