import type { Metadata } from "next";
import LoadingPage from "@/auth/loading/LoadingPage";
//clerck auth
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
//styles
import { StyledEngineProvider } from "@mui/material";
import ThemeProviderWrapper from "@/theme/muiTheme/theme";
import "@/theme/tailwindTheme/globals.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id={"__next"}>
        <ClerkProvider>
          <StyledEngineProvider injectFirst>
            <ThemeProviderWrapper>
              <ClerkLoading>
                <LoadingPage />
              </ClerkLoading>
              <ClerkLoaded>
                {/* <LoadingPage /> */}
                {children}
              </ClerkLoaded>
            </ThemeProviderWrapper>
          </StyledEngineProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
